robotiq_140_description:
  ubuntu:
  - ros-humble-robotiq-140-description
ur:
  ubuntu:
  - ros-humble-ur
ur_bringup:
  ubuntu:
  - ros-humble-ur-bringup
ur_client_library:
  ubuntu:
  - ros-humble-ur-client-library
ur_dashboard_msgs:
  ubuntu:
  - ros-humble-ur-dashboard-msgs
ur_description:
  ubuntu:
  - ros-humble-ur-description
ur_moveit_config:
  ubuntu:
  - ros-humble-ur-moveit-config
ur_msgs:
  ubuntu:
  - ros-humble-ur-msgs
ur_controllers:
  ubuntu:
  - ros-humble-ur-controllers
ur_robot_driver:
  ubuntu:
  - ros-humble-ur-robot-driver
ur_calibration:
  ubuntu:
  - ros-humble-ur-calibration
